In [ ]:
# http://notepad.pw/chandanpro

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

from sklearn.metrics import accuracy_score

data = pd.read_csv(r'C:\Users\KIIT_Intern\Documents\Data.csv')


from sklearn.preprocessing import LabelEncoder
lenc = LabelEncoder()

In [2]:
data.head()

,customer_id,vintage,age,gender,dependents,occupation,city,customer_nw_category,branch_code,days_since_last_transaction,...,previous_month_end_balance,average_monthly_balance_prevQ,average_monthly_balance_prevQ2,current_month_credit,previous_month_credit,current_month_debit,previous_month_debit,current_month_balance,previous_month_balance,churn
0,1,3135,66,Male,0.0,self_employed,187.0,2,755,224.0,...,1458.71,1458.71,1449.07,0.20,0.20,0.20,0.20,1458.71,1458.71,0
1,2,310,35,Male,0.0,self_employed,NaN,2,3214,60.0,...,8704.66,7799.26,12419.41,0.56,0.56,5486.27,100.56,6496.78,8787.61,0
2,4,2356,31,Male,0.0,salaried,146.0,2,41,NaN,...,5815.29,4910.17,2815.94,0.61,0.61,6046.73,259.23,5006.28,5070.14,0
3,5,478,90,NaN,NaN,self_employed,1020.0,2,582,147.0,...,2291.91,2084.54,1006.54,0.47,0.47,0.47,2143.33,2291.91,1669.79,1
4,6,2531,42,Male,2.0,self_employed,1494.0,3,388,58.0,...,1401.72,1643.31,1871.12,0.33,714.61,588.62,1538.06,1157.15,1677.16,1

In [ ]:
data.drop('customer_id',axis=1,inplace=True)
data.drop('gender',axis=1,inplace=True)

In [5]:
X = data.iloc[:,:-1]
Y = data.iloc[:,-1]

In [11]:
from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=0)


from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)

In [ ]:
X.loc[X['Item_Description'].str.contains('Auto Leasing'), 'Item_Description'] = '3'
X['Item_Description']=lenc.fit_transform(X['Item_Description'])

from sklearn.model_selection import train_test_split
X_train,X_test,Y_train,Y_test = train_test_split(X,Y,test_size=0.33,random_state=0)

from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
X_train = sc_x.fit_transform(X_train)
X_test = sc_x.transform(X_test)
from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier(n_estimators = 40, criterion = 'entropy', random_state = 0)
classifier.fit(X_train, Y_train)

Y_pred = classifier.predict(X_test)
acc = accuracy_score(Y_test,Y_pred)
print('Accuracy :',acc*100,'%')
test = pd.read_csv(r'C:\Users\nEW u\Desktop\dataset\Test.csv')

test['GL_Code'] = test['GL_Code'].str.extract('(\d+)').astype(int)
test['Vendor_Code'] = test['Vendor_Code'].str.extract('(\d+)').astype(int)
#test['Product_Category'] = test['Product_Category'].str.extract('(\d+)').astype(int)
iD = list(test['Inv_Id'])
test.drop('Inv_Id',axis=1,inplace=True)

Casscade(test)
test.loc[test['Item_Description'].str.contains('Auto Leasing'), 'Item_Description'] = '3'
#test["Item_Description"] = test["Item_Description"].str.split("- ", expand = True)[2]
#lenc = LabelEncoder()
test['Item_Description']=lenc.fit_transform(test['Item_Description'])
#test = test.iloc[:,:-1]           #Remove this later
sc_x = StandardScaler()
test = sc_x.fit_transform(test)
Y_est = classifier.predict(test)
print(Y_est)